version: "3.9"

services:

  discordbot:
    container_name: discordbot
    build:
      context: ./src
      dockerfile: Dockerfile
    environment:
      - TZ=Turkey
    env_file:
      - .env
    volumes:
       - .:/discord_home
    ports:
      - 8443:8443
    stdin_open: true
    tty: true
    restart: on-failure