version: "3.9"

services:

  discordbot:
    container_name: discordbot
    build: .
    image: discordbot
    environment:
      - TZ=Turkey
    env_file:
      - .env.build
    ports:
      - 8443:8443
    stdin_open: true
    tty: true
    restart: on-failure